### ISSUE TITLE
Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found

### ISSUE THREAD

**Issue by checkm94** [presscodes/kirki#2417]
### Issue description:

Frontend (console):

`Failed to load resource: the server responded with a status of 500 ()`

Backend (log):

```[30-Dec-2021 13:25:00 UTC] PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found in /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170
Stack trace:
#0 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css(Array)
#1 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls('shoptimizer_con...')
#2 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3 /home/edizion/public_html/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline('')
#4 /home/edizion/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /home/edizion/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /home/edizion/public_html/wp-includes/general-template.php(3015): do_action('wp_head' in /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170
[30-Dec-2021 13:26:55 UTC] PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found in /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170
Stack trace:
#0 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css(Array)
#1 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls('shoptimizer_con...')
#2 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3 /home/edizion/public_html/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline('')
#4 /home/edizion/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /home/edizion/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /home/edizion/public_html/wp-includes/general-template.php(3015): do_action('wp_head' in /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170
[30-Dec-2021 13:33:46 UTC] PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found in /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170
Stack trace:
#0 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css(Array)
#1 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls('shoptimizer_con...')
#2 /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3 /home/edizion/public_html/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline('')
#4 /home/edizion/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /home/edizion/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /home/edizion/public_html/wp-includes/general-template.php(3015): do_action('wp_head' in /home/edizion/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170
```

### Version used:
Updated to version 4.0 one hour ago. Installed with shoptimizer theme.

**Comment by mapsteps** [comment]
Seems that there is an issue with the Shoptimizer theme & Kirki 4 specifically. We're trying to get our hands on a copy of the theme now & are going to check if this is something we can fix on our end.

Please take a moment to also notify them about the issue. It might be something they'll be able to fix more quickly on their end.

Thank you.

**Comment by mapsteps** [comment]
Closing this for now as it's a dupliate https://github.com/kirki-framework/kirki/issues/2416 We're still looking into this of course :)

**Comment by contactjavas** [comment]
Hi @checkm94 , please update to `4.0.3`. That fixes the issue.
In case updating through WordPress is failed, please download it manually [here](https://downloads.wordpress.org/plugin/kirki.4.0.3.zip)

For next discussion about this issue, please go to #2416 
Thanks!

**Comment by checkm94** [comment]
Updating fixed the issue. Thank you.
