### ISSUE TITLE
Fatal error when upgrade to php 8 environment

### ISSUE THREAD

**Issue by nowarah** [presscodes/kirki#2492]
### Issue description:
when upgrading to php 8 it shows the error below

### Version used:
 4.0.22
I use knowall theme that have the kirki package, do you think you can figure out what I can do to solve this?

### Using `theme_mods` or `options`?
`theme_mods`

### PHP error messages that might be related
```bash
[26-Sep-2022 21:35:29 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Downloader.php:99
Stack trace:
#0 /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Downloader.php(44): Kirki\Module\Webfonts\Downloader->get_local_files_from_css()
#1 /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Downloader.php(32): Kirki\Module\Webfonts\Downloader->get_local_font_styles()
#2 /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Embed.php(153): Kirki\Module\Webfonts\Downloader->get_styles()
#3 /home/help/public_html/wp-includes/class-wp-hook.php(307): Kirki\Module\Webfonts\Embed->the_css()
#4 /home/help/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/help/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-css/src/CSS.php(298): do_action()
#7 /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-css/src/CSS.php(185): Kirki\Module\CSS->print_styles()
#8 /home/help/public_html/wp-includes/class-wp-hook.php(307): Kirki\Module\CSS->print_styles_inline()
#9 /home/help/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#10 /home/help/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#11 /home/help/public_html/wp-includes/general-template.php(3042): do_action()
#12 /home/help/public_html/wp-content/themes/knowall-child/header.php(9): wp_head()
#13 /home/help/public_html/wp-includes/template.php(770): require_once('/home/help/publ...')
#14 /home/help/public_html/wp-includes/template.php(716): load_template()
#15 /home/help/public_html/wp-includes/general-template.php(48): locate_template()
#16 /home/help/public_html/wp-content/themes/knowall/hkb-templates/hkb-single.php(8): get_header()
#17 /home/help/public_html/wp-includes/template-loader.php(106): include('/home/help/publ...')
#18 /home/help/public_html/wp-blog-header.php(19): require_once('/home/help/publ...')
#19 /home/help/public_html/index.php(17): require('/home/help/publ...')
#20 {main}
  thrown in /home/help/public_html/wp-content/themes/knowall/inc/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Downloader.php on line 99
```

### JS error messages that might be related
```bash

```

### Code to reproduce the issue (config + field(s))
```php

```

**Comment by Noarah** [comment]
Update: fixed with tyhe correct font url path

**Comment by Noarah** [comment]
sorry it's not fixed yet!

**Comment by Noarah** [comment]
reopen
