### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): on wp dist-archive 

### ISSUE THREAD

**Issue by shahadul878** [presscodes/kirki#2537]
### Issue description:
.
Issues with wp dist-archive cli command

### Version used:
PHP:8.3

### Using `theme_mods` or `options`?
`theme_mods`

### PHP error messages that might be related
```bash
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field-dimensions/src/Dimensions.php:105
Stack trace:
#0 /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field-dimensions/src/Dimensions.php(105): count()
#1 /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field/src/Field.php(104): Kirki\Field\Dimensions->init()
#2 /home/shahadul/Desktop/giftly/wp-content/themes/giftly/inc/customizer/panels/giftly-customize-layout.php(554): Kirki\Field->__construct()
#3 /home/shahadul/Desktop/giftly/wp-content/themes/giftly/inc/customizer/class-giftly-customize.php(121): require('...')
#4 /home/shahadul/Desktop/giftly/wp-includes/class-wp-hook.php(324): Giftly_Customize::register()
#5 /home/shahadul/Desktop/giftly/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/shahadul/Desktop/giftly/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home/shahadul/Desktop/giftly/wp-settings.php(700): do_action()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1375): require('...')
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1294): WP_CLI\Runner->load_wordpress()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#13 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#14 /usr/local/bin/wp(4): include('...')
#15 {main}
  thrown in /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field-dimensions/src/Dimensions.php on line 105
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field-dimensions/src/Dimensions.php:105
Stack trace:
#0 /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field-dimensions/src/Dimensions.php(105): count()
#1 /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field/src/Field.php(104): Kirki\Field\Dimensions->init()
#2 /home/shahadul/Desktop/giftly/wp-content/themes/giftly/inc/customizer/panels/giftly-customize-layout.php(554): Kirki\Field->__construct()
#3 /home/shahadul/Desktop/giftly/wp-content/themes/giftly/inc/customizer/class-giftly-customize.php(121): require('...')
#4 /home/shahadul/Desktop/giftly/wp-includes/class-wp-hook.php(324): Giftly_Customize::register()
#5 /home/shahadul/Desktop/giftly/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/shahadul/Desktop/giftly/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home/shahadul/Desktop/giftly/wp-settings.php(700): do_action()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1375): require('...')
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1294): WP_CLI\Runner->load_wordpress()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#13 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#14 /usr/local/bin/wp(4): include('...')
#15 {main}
  thrown in /home/shahadul/Desktop/giftly/wp-content/plugins/kirki/kirki-packages/field-dimensions/src/Dimensions.php on line 105
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.```

**Comment by wprashed** [comment]
##### Set a Default Value (as Array) in the Dimensions Field

Ensure your Kirki field has a proper default like this:

```
[
    'settings' => 'your_dimensions_setting',
    'label'    => __( 'Spacing', 'textdomain' ),
    'section'  => 'your_section_id',
    'type'     => 'kirki-dimensions',
    'default'  => [
        'top'    => '',
        'right'  => '',
        'bottom' => '',
        'left'   => '',
    ],
]
```

##### Fix Existing Corrupt Setting in theme_mods (Optional)
If your setting is already saved as a string, you can manually reset or remove it. Use this in a temporary plugin or functions.php:

```
add_action( 'after_setup_theme', function () {
    $value = get_theme_mod( 'your_dimensions_setting' );

    if ( ! is_array( $value ) ) {
        remove_theme_mod( 'your_dimensions_setting' );
    }
});
```
